### ISSUE TITLE
Cocos2d-JS-v3-Tutorial-6---Multi-Resolution-Support/TutorialCCJSYouTube/main.js

### ISSUE THREAD

**Issue by yigemajia** [SonarSystems/Cocos2d-JS-v3-Tutorial-6---Multi-Resolution-Support#1]
line 78

if (cc.view.getFrameSize().width >= 1136 || cc.view.getFrameSize.height >= 1136)

 should be 

if (cc.view.getFrameSize().width >= 1136 || cc.view.getFrameSize().height >= 1136)

**Comment by SonarSystems** [comment]
Indeed it should
